### ISSUE TITLE
I2S in split patches do not apply correctly

### ISSUE THREAD

**Issue by abhijit-mahajani-imgtec** [CreatorDev/lede-source#8]
Is it still needed? If so needs to be merged onto new base but has been left out for now.

0113-ASoC-img-Add-split-i2s-in.patch

**Comment by Shpinkso** [comment]
A requirement for near field beam forming, probably will not get around to this, realistically

**Comment by Ham22** [comment]
Note this patch is a bit of a hack and would never be upstreamable in it's current form. I believe it's for an obsolete requirement so we can just close for now?
